Add ability to toggle between bitnami and bitnamilegacy
Only copy one tag at a time
Log and continue on error

diff --git a/.github/workflows/crane.yml b/.github/workflows/crane.yml
--- a/.github/workflows/crane.yml
+++ b/.github/workflows/crane.yml
@@ -1,4 +1,4 @@
-name: Copy tags from docker.io/bitnamilegacy to GHCR
+name: Copy tags from Bitnami to GHCR
 
 on:
   workflow_dispatch:
@@ -7,6 +7,11 @@ on:
         description: "Comma-separated list of container names to sync (e.g: keycloak, nats, valkey)"
         required: true
         type: string
+      legacy:
+        description: "Whether or not to sync from Bitnami Legacy (default: true)"
+        required: false
+        default: true
+        type: boolean
 
 permissions: {}
 
@@ -56,7 +61,11 @@ jobs:
       - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
       - uses: imjasonh/setup-crane@31b88efe9de28ae0ffa220711af4b60be9435f6e # v0.4
       - name: Copy ${{ matrix.image }}
+        env:
+          IMAGE: ${{ matrix.image }}
+          REPO: ${{ github.event.inputs.legacy == 'true' && 'docker.io/bitnamilegacy' || 'docker.io/bitnami' }}
         run: |-
-          crane copy --all-tags \
-            docker.io/bitnamilegacy/${{ matrix.image }} \
-            ghcr.io/${{ github.repository_owner }}/bitnami-oss/${{ matrix.image }}
+          for tag in $(crane ls ${REPO}/${IMAGE}); do
+            crane copy ${REPO}/${IMAGE}:${tag} \
+              ghcr.io/${{ github.repository_owner }}/bitnami-oss/${{ matrix.image }}:$tag || echo "::warning::Failed to copy ${REPO}/${IMAGE}:${tag}"
+          done
